# Generated by Django 3.0 on 2020-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200622_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
